//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightSign.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BrightSign.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        public static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        public static string please_try_again {
            get {
                return ResourceManager.GetString("please_try_again", resourceCulture);
            }
        }
        
        public static string something_went_wrong {
            get {
                return ResourceManager.GetString("something_went_wrong", resourceCulture);
            }
        }
        
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        public static string check_your_network {
            get {
                return ResourceManager.GetString("check_your_network", resourceCulture);
            }
        }
        
        public static string command_successful {
            get {
                return ResourceManager.GetString("command_successful", resourceCulture);
            }
        }
        
        public static string search_error {
            get {
                return ResourceManager.GetString("search_error", resourceCulture);
            }
        }
        
        public static string enter_ipaddress_desc {
            get {
                return ResourceManager.GetString("enter_ipaddress_desc", resourceCulture);
            }
        }
        
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        public static string auth_required {
            get {
                return ResourceManager.GetString("auth_required", resourceCulture);
            }
        }
        
        public static string devicealreadypresenterror {
            get {
                return ResourceManager.GetString("devicealreadypresenterror", resourceCulture);
            }
        }
        
        public static string labelerror {
            get {
                return ResourceManager.GetString("labelerror", resourceCulture);
            }
        }
        
        public static string dataerror {
            get {
                return ResourceManager.GetString("dataerror", resourceCulture);
            }
        }
        
        public static string selectbrightsign {
            get {
                return ResourceManager.GetString("selectbrightsign", resourceCulture);
            }
        }
        
        public static string exit_the_application {
            get {
                return ResourceManager.GetString("exit_the_application", resourceCulture);
            }
        }
        
        public static string addedtolist {
            get {
                return ResourceManager.GetString("addedtolist", resourceCulture);
            }
        }
        
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        public static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
        
        public static string savedsuccessfully {
            get {
                return ResourceManager.GetString("savedsuccessfully", resourceCulture);
            }
        }
        
        public static string devicedetailserror {
            get {
                return ResourceManager.GetString("devicedetailserror", resourceCulture);
            }
        }
        
        public static string nopresentationerror {
            get {
                return ResourceManager.GetString("nopresentationerror", resourceCulture);
            }
        }
    }
}
